USE CarParsing

CREATE TABLE MODELDATA
(
	[MODELID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[MODELCODE] NVARCHAR(50) UNIQUE NOT NULL,
	[MODELNAME] NVARCHAR(50) NULL,
	[MODELDATERANGE] NVARCHAR(50) NULL,
	[MODELPICKINGCODE] NVARCHAR(50) NULL,
);

CREATE TABLE MODELEQUIPMENT
(
	[MODELEQUIPMENTID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[MODELCODE] NVARCHAR(50) NOT NULL,
	[DATE] NVARCHAR(50) NULL,
	[EQUIPMENTCODE] NVARCHAR(50) UNIQUE NOT NULL,
	[ATM,MTM] NVARCHAR(50) NULL,
	[BACK DOOR] NVARCHAR(50) NULL,
	[BODY] NVARCHAR(50) NULL,
	[BODY 1] NVARCHAR(50) NULL,
	[BODY 2] NVARCHAR(50) NULL,
	[BODY SHAPE] NVARCHAR(50) NULL,
	[BUILDING CONDITION] NVARCHAR(50) NULL,
	[CAB] NVARCHAR(50) NULL,
	[CATEGORY] NVARCHAR(50) NULL,
	[COOLER] NVARCHAR(50) NULL,
	[DECK] NVARCHAR(50) NULL,
	[DECK(MATERIAL)] NVARCHAR(50) NULL,
	[DECK,CAB] NVARCHAR(50) NULL,
	[DESTINATION] NVARCHAR(50) NULL,
	[DESTINATION 1] NVARCHAR(50) NULL,
	[DESTINATION 2] NVARCHAR(50) NULL,
	[DRIVER S LICENSE] NVARCHAR(50) NULL,
	[DRIVER S POSITION] NVARCHAR(50) NULL,
	[EMISSION REGULATION] NVARCHAR(50) NULL,
	[ENGINE 1] NVARCHAR(50) NULL,
	[ENGINE 2] NVARCHAR(50) NULL,
	[FUEL INDUCTION] NVARCHAR(50) NULL,
	[GEAR SHIFT TYPE] NVARCHAR(50) NULL,
	[GRADE] NVARCHAR(50) NULL,
	[GRADE MARK] NVARCHAR(50) NULL,
	[INCOMPLETE VEHICLES] NVARCHAR(50) NULL,
	[LOADING CAPACITY] NVARCHAR(50) NULL,
	[MODEL MARK] NVARCHAR(50) NULL,
	[NO.OF DOORS] NVARCHAR(50) NULL,
	[PRODUCT] NVARCHAR(50) NULL,
	[REAR SUSPENTION] NVARCHAR(50) NULL,
	[REAR TIRE] NVARCHAR(50) NULL,
	[ROLL BAR] NVARCHAR(50) NULL,
	[ROOF] NVARCHAR(50) NULL,
	[SEAT TYPE] NVARCHAR(50) NULL,
	[SEATING CAPACITY] NVARCHAR(50) NULL,
	[SIDE WINDOW] NVARCHAR(50) NULL,
	[TOP,BACK DOOR] NVARCHAR(50) NULL,
	[TRANSMISSION MODEL] NVARCHAR(50) NULL,
	[TRUCK OR VAN] NVARCHAR(50) NULL,
	[VEHICLE MODEL] NVARCHAR(50) NULL,	
	FOREIGN KEY ([MODELCODE]) REFERENCES [MODELDATA] ([MODELCODE])
);

CREATE TABLE SPAREPARTGROUP
(
	[SPAREPARTGROUPID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[EQUIPMENTCODE] NVARCHAR(50) NOT NULL,
	[SPAREPARTGROUPNAME] NVARCHAR(50) UNIQUE NOT NULL,
	FOREIGN KEY ([EQUIPMENTCODE]) REFERENCES [MODELEQUIPMENT] ([EQUIPMENTCODE])
);

CREATE TABLE SPAREPARTSUBGROUP
(
	[SPAREPARTSUBGROUPID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[SPAREPARTSUBGROUPNAME] NVARCHAR(150) UNIQUE NOT NULL,
	[SPAREPARTGROUPNAME] NVARCHAR(50) NOT NULL,
	FOREIGN KEY ([SPAREPARTGROUPNAME]) REFERENCES SPAREPARTGROUP ([SPAREPARTGROUPNAME])
);

CREATE TABLE SPAREPARTDATA
(
	[SPAREPARTID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[SPAREPARTCODE] NVARCHAR(50) NULL,
	[SPAREPARTCOUNT] INT NULL,
	[SPAREPARTINFO] NVARCHAR(100) NULL,
	[SPAREPARTTREECODE] NVARCHAR(50) NULL,
	[SPAREPARTTREE] NVARCHAR(100) NULL,
	[SPAREPARTDATE] NVARCHAR(50) NULL,
	[SPAREPARTSUBGROUPNAME] NVARCHAR(150) NOT NULL,
	[SPAREPARTSUBGROUPLINK] NVARCHAR(200) NOT NULL,
	[SPAREPARTIMAGENAME] NVARCHAR(50) NULL,
	FOREIGN KEY ([SPAREPARTSUBGROUPNAME]) REFERENCES [SPAREPARTSUBGROUP] ([SPAREPARTSUBGROUPNAME])
);


USE [CarParsing]
GO

SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [IndexCodeName] ON [dbo].[MODELDATA]
(
	[MODELCODE] ASC,
	[MODELNAME] ASC
)
INCLUDE([MODELID],[MODELDATERANGE],[MODELPICKINGCODE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


USE [CarParsing]
GO

SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [ModelEquipmentIdCode] ON [dbo].[MODELEQUIPMENT]
(
	[MODELEQUIPMENTID] ASC,
	[MODELCODE] ASC
)
INCLUDE([DATE],[EQUIPMENTCODE],[ATM,MTM],[BACK DOOR],[BODY],[BODY 1],[BODY 2],[BODY SHAPE],[BUILDING CONDITION],[CAB],[CATEGORY],[COOLER],[DECK],[DECK(MATERIAL)],[DECK,CAB],[DESTINATION],[DESTINATION 1],[DESTINATION 2],[DRIVER S LICENSE],[DRIVER S POSITION],[EMISSION REGULATION],[ENGINE 1],[ENGINE 2],[FUEL INDUCTION],[GEAR SHIFT TYPE],[GRADE],[GRADE MARK],[INCOMPLETE VEHICLES],[LOADING CAPACITY],[MODEL MARK],[NO.OF DOORS],[PRODUCT],[REAR SUSPENTION],[REAR TIRE],[ROLL BAR],[ROOF],[SEAT TYPE],[SEATING CAPACITY],[SIDE WINDOW],[TOP,BACK DOOR],[TRANSMISSION MODEL],[TRUCK OR VAN],[VEHICLE MODEL]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

USE [CarParsing]
GO

SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [PartIdCodeSub] ON [dbo].[SPAREPARTDATA]
(
	[SPAREPARTID] ASC,
	[SPAREPARTCODE] ASC,
	[SPAREPARTSUBGROUPNAME] ASC
)
INCLUDE([SPAREPARTCOUNT],[SPAREPARTINFO],[SPAREPARTTREECODE],[SPAREPARTTREE],[SPAREPARTDATE],[SPAREPARTSUBGROUPLINK],[SPAREPARTIMAGENAME]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



