USE CarParcing

CREATE TABLE MODELDATA
(
	[MODELID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[MODELCODE] NVARCHAR(50) UNIQUE NOT NULL,
	[MODELNAME] NVARCHAR(50) NOT NULL,
	[MODELDATERANGE] NVARCHAR(50) NOT NULL,
	[MODELPICKINGCODE] NVARCHAR(50) NOT NULL,
);

CREATE TABLE MODELEQUIPMENT
(
	[MODELEQUIPMENTID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[MODELCODE] NVARCHAR(50) NOT NULL,
	[DATE] NVARCHAR(50) NULL,
	[EQUIPMENTCODE] NVARCHAR(50) UNIQUE NULL,
	[ATM,MTM] NVARCHAR(50) NULL,
	[BACK DOOR] NVARCHAR(50) NULL,
	[BODY] NVARCHAR(50) NULL,
	[BODY 1] NVARCHAR(50) NULL,
	[BODY 2] NVARCHAR(50) NULL,
	[BODY SHAPE] NVARCHAR(50) NULL,
	[BUILDING CONDITION] NVARCHAR(50) NULL,
	[CAB] NVARCHAR(50) NULL,
	[CATEGORY] NVARCHAR(50) NULL,
	[COOLER] NVARCHAR(50) NULL,
	[DECK] NVARCHAR(50) NULL,
	[DECK(MATERIAL)] NVARCHAR(50) NULL,
	[DECK,CAB] NVARCHAR(50) NULL,
	[DESTINATION] NVARCHAR(50) NULL,
	[DESTINATION 1] NVARCHAR(50) NULL,
	[DESTINATION 2] NVARCHAR(50) NULL,
	[DRIVER S LICENSE] NVARCHAR(50) NULL,
	[DRIVER S POSITION] NVARCHAR(50) NULL,
	[EMISSION REGULATION] NVARCHAR(50) NULL,
	[ENGINE 1] NVARCHAR(50) NULL,
	[ENGINE 2] NVARCHAR(50) NULL,
	[FUEL INDUCTION] NVARCHAR(50) NULL,
	[GEAR SHIFT TYPE] NVARCHAR(50) NULL,
	[GRADE] NVARCHAR(50) NULL,
	[GRADE MARK] NVARCHAR(50) NULL,
	[INCOMPLETE VEHICLES] NVARCHAR(50) NULL,
	[LOADING CAPACITY] NVARCHAR(50) NULL,
	[MODEL MARK] NVARCHAR(50) NULL,
	[NO.OF DOORS] NVARCHAR(50) NULL,
	[PRODUCT] NVARCHAR(50) NULL,
	[REAR SUSPENTION] NVARCHAR(50) NULL,
	[REAR TIRE] NVARCHAR(50) NULL,
	[ROLL BAR] NVARCHAR(50) NULL,
	[ROOF] NVARCHAR(50) NULL,
	[SEAT TYPE] NVARCHAR(50) NULL,
	[SEATING CAPACITY] NVARCHAR(50) NULL,
	[SIDE WINDOW] NVARCHAR(50) NULL,
	[TOP,BACK DOOR] NVARCHAR(50) NULL,
	[TRANSMISSION MODEL] NVARCHAR(50) NULL,
	[TRUCK OR VAN] NVARCHAR(50) NULL,
	[VEHICLE MODEL] NVARCHAR(50) NULL,	
	FOREIGN KEY ([MODELCODE]) REFERENCES [MODELDATA] ([MODELCODE])
);

CREATE TABLE SPAREPARTGROUP
(
	[SPAREPARTGROUPID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[EQUIPMENTCODE] NVARCHAR(50)  UNIQUE NOT NULL,
	[SPAREPARTGROUPNAME] NVARCHAR(50) UNIQUE NOT NULL,
	FOREIGN KEY ([EQUIPMENTCODE]) REFERENCES [MODELEQUIPMENT] ([EQUIPMENTCODE])
);

CREATE TABLE SPAREPARTSUBGROUP
(
	[SPAREPARTSUBGROUPID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[SPAREPARTSUBGROUPNAME] NVARCHAR(100) UNIQUE NOT NULL,
	[SPAREPARTGROUPNAME] NVARCHAR(50) NOT NULL,
	FOREIGN KEY ([SPAREPARTGROUPNAME]) REFERENCES SPAREPARTGROUP ([SPAREPARTGROUPNAME])
);

CREATE TABLE SPAREPARTDATA
(
	[SPAREPARTID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[SPAREPARTCODE] NVARCHAR(50) NULL,
	[SPAREPARTCOUNT] INT NULL,
	[SPAREPARTINFO] NVARCHAR(100) NULL,
	[SPAREPARTTREECODE] NVARCHAR(50) NULL,
	[SPAREPARTTREE] NVARCHAR(100) NULL,
	[SPAREPARTDATE] NVARCHAR(50) NULL,
	[SPAREPARTSUBGROUPID] INT NOT NULL,
	[SPAREPARTSUBGROUPLINK] NVARCHAR(200) NOT NULL,
	[SPAREPARTIMAGENAME] NVARCHAR(50) NULL,
	FOREIGN KEY ([SPAREPARTSUBGROUPID]) REFERENCES [SPAREPARTSUBGROUP] ([SPAREPARTSUBGROUPID])
);