USE CarParcing


GO
CREATE PROCEDURE ModelDataAdd 
	@modelCode NVARCHAR(50),
	@modelName NVARCHAR(50),
	@modelDateRange NVARCHAR(50),
	@modelPickingCode NVARCHAR(50)
AS
INSERT INTO [MODELDATA] ([MODELCODE], [MODELNAME], [MODELDATERANGE], [MODELPICKINGCODE]) 
VALUES (@modelCode, @modelName, @modelDateRange, @modelPickingCode)


GO
CREATE PROCEDURE SparePartGroupAdd
	@equipmentCode NVARCHAR(50),
	@sparePartGroupName NVARCHAR(50)
AS	
BEGIN
	IF NOT EXISTS (SELECT * FROM SPAREPARTGROUP
					WHERE [SPAREPARTGROUPNAME]= @sparePartGroupName)
	BEGIN
		INSERT INTO [SPAREPARTGROUP] ([EQUIPMENTCODE], [SPAREPARTGROUPNAME]) 
		VALUES (@equipmentCode, @sparePartGroupName)
	END
END


GO
CREATE PROCEDURE SparePartSubGroupAdd
	@sparePartSubGroup NVARCHAR(100),
	@sparePartGroup NVARCHAR(50)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM SPAREPARTSUBGROUP
					WHERE [SPAREPARTSUBGROUPNAME] = @sparePartSubGroup)
	BEGIN
		INSERT INTO [SPAREPARTSUBGROUP] ([SPAREPARTSUBGROUPNAME], [SPAREPARTGROUPNAME]) 
		VALUES (@sparePartSubGroup,@sparePartGroup)
	END
END


GO
CREATE PROCEDURE SparePartDataAdd	
	@sparePartCode NVARCHAR(50) = NULL,
	@sparePartCount INT = 0,
	@sparePartInfo NVARCHAR(100) = NULL,
	@sparePartTreeCode NVARCHAR(50) = NULL,
	@sparePartTree NVARCHAR(100) = NULL,
	@sparePartDate NVARCHAR(50) = NULL,
	@sparePartSubGroupName NVARCHAR(150),
	@sparePartSubGroupLink NVARCHAR(200),
	@sparePartImageName NVARCHAR(50) = NULL
AS
INSERT INTO SPAREPARTDATA ([SPAREPARTCODE], [SPAREPARTCOUNT], [SPAREPARTINFO], [SPAREPARTTREECODE], [SPAREPARTTREE], [SPAREPARTDATE], [SPAREPARTSUBGROUPLINK], [SPAREPARTIMAGENAME]) 
VALUES (@sparePartCode, @sparePartCount, @sparePartInfo, @sparePartTreeCode, @sparePartTree, @sparePartDate, @sparePartSubGroupLink, @sparePartImageName)
