USE CarParcing
TRUNCATE TABLE SPAREPARTDATA
TRUNCATE TABLE SPAREPARTSUBGROUP
TRUNCATE TABLE SPAREPARTGROUP
TRUNCATE TABLE MODELEQUIPMENT
TRUNCATE TABLE MODELDATA

USE CarParcing
DROP TABLE SPAREPARTDATA
DROP TABLE SPAREPARTSUBGROUP
DROP TABLE SPAREPARTGROUP
DROP TABLE MODELEQUIPMENT
DROP TABLE MODELDATA

USE CarParcing
DROP PROCEDURE ModelDataAdd
DROP PROCEDURE SparePartDataADD
DROP PROCEDURE SparePartGroupAdd
DROP PROCEDURE SparePartSubGroupAdd
DROP PROCEDURE checkValueInGroup
