

USE CarParsing
DROP TABLE SPAREPARTDATA
DROP TABLE SPAREPARTSUBGROUP
DROP TABLE SPAREPARTGROUP
DROP TABLE MODELEQUIPMENT
DROP TABLE MODELDATA

USE CarParsing
DROP PROCEDURE ModelDataAdd
DROP PROCEDURE SparePartDataADD
DROP PROCEDURE SparePartGroupAdd
DROP PROCEDURE SparePartSubGroupAdd
