USE CarDetails

CREATE TABLE ModelData
(
	[MODELID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[MODELCODE] INT  NOT NULL,
	[MODELNAME] NVARCHAR(50) NOT NULL,
	[MODELDATERANGE] NVARCHAR(50) NOT NULL,
	[MODELPICKINGCODE] NVARCHAR(50) NOT NULL,
);

CREATE TABLE ModelPicking
(
	[PICKINGID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[MODELCODE] INT NOT NULL,
	[DATE] NCHAR (20) NULL,
	[EQUIPMENT] NCHAR (20) NULL,
	[ATM,MTM] NVARCHAR(50) NULL,
	[BACK DOOR] NVARCHAR(50) NULL,
	[BODY] NVARCHAR(50) NULL,
	[BODY 1] NVARCHAR(50) NULL,
	[BODY 2] NVARCHAR(50) NULL,
	[BODY SHAPE] NVARCHAR(50) NULL,
	[BUILDING CONDITION] NVARCHAR(50) NULL,
	[CAB] NVARCHAR(50) NULL,
	[CATEGORY] NVARCHAR(50) NULL,
	[COOLER] NVARCHAR(50) NULL,
	[DECK] NVARCHAR(50) NULL,
	[DECK(MATERIAL)] NVARCHAR(50) NULL,
	[DECK,CAB] NVARCHAR(50) NULL,
	[DESTINATION] NVARCHAR(50) NULL,
	[DESTINATION 1] NVARCHAR(50) NULL,
	[DESTINATION 2] NVARCHAR(50) NULL,
	[DRIVER S LICENSE] NVARCHAR(50) NULL,
	[DRIVER S POSITION] NVARCHAR(50) NULL,
	[EMISSION REGULATION] NVARCHAR(50) NULL,
	[ENGINE 1] NVARCHAR(50) NULL,
	[ENGINE 2] NVARCHAR(50) NULL,
	[FUEL INDUCTION] NVARCHAR(50) NULL,
	[GEAR SHIFT TYPE] NVARCHAR(50) NULL,
	[GRADE] NVARCHAR(50) NULL,
	[GRADE MARK] NVARCHAR(50) NULL,
	[INCOMPLETE VEHICLES] NVARCHAR(50) NULL,
	[LOADING CAPACITY] NVARCHAR(50) NULL,
	[MODEL MARK] NVARCHAR(50) NULL,
	[NO.OF DOORS] NVARCHAR(50) NULL,
	[PRODUCT] NVARCHAR(50) NULL,
	[REAR SUSPENTION] NVARCHAR(50) NULL,
	[REAR TIRE] NVARCHAR(50) NULL,
	[ROLL BAR] NVARCHAR(50) NULL,
	[ROOF] NVARCHAR(50) NULL,
	[SEAT TYPE] NVARCHAR(50) NULL,
	[SEATING CAPACITY] NVARCHAR(50) NULL,
	[SIDE WINDOW] NVARCHAR(50) NULL,
	[TOP,BACK DOOR] NVARCHAR(50) NULL,
	[TRANSMISSION MODEL] NVARCHAR(50) NULL,
	[TRUCK OR VAN] NVARCHAR(50) NULL,
	[VEHICLE MODEL] NVARCHAR(50) NULL
);

CREATE TABLE PickingGroups
(
	[PICKINGGROUPID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[PICKINGID] INT NOT NULL,
	[PICKINGGROUPNAME] NVARCHAR(50) NOT NULL
);

CREATE TABLE PickingSubGroups
(
	[PICKINGSUBGROUPID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[PICKINGSUBGROUPNAME] NVARCHAR(50) NOT NULL,
	[PICKINGGROUPID] INT NOT NULL
);

CREATE TABLE PickingData
(
	[PICKINGID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[PICKINGCODE] NVARCHAR(50) NULL,
	[PICKINGCOUNT] INT NULL,
	[PICKINGINFO] NVARCHAR(50) NULL,
	[PICKINGTREECODE] NVARCHAR(50) NULL,
	[PICKINGTREE] NVARCHAR(50) NULL,
	[PICKINGDATE] NVARCHAR(50) NULL,
	[PICKINGGROUPID] INT NOT NULL,
	[PICKINGSUBGROUPLINK] NVARCHAR(100) NOT NULL,
	[PICKINGIMAGENAME] NVARCHAR(50) NULL
);